<?php

$names = [
	["spectacled bear","andean bear"],
	["brown spider monkey","variagated spider monkey"],
	["south american tapir","brazilian tapir","lowland tapir"],
	["mountain lion","cougar","puma"],
	["asian short clawed otter", "oriental small clawed otter", "oriental short clawed otter", "asian small clawed otter"],
	["african buffalo", "cape buffalo"],
	["wildebeest","gnu"],
	["north american brown bear","grizzly bear","grizzly"],
	["beluga whale","white whale"],
	["fruit bat","flying fox"],
	["bearcat","binturong"],
	["raccoon dog","tanuki"],
	["coati","coatimundi","south american coati","ring tailed coati"],
	["red panda", "lesser panda", "firefox", "red bear cat", "red cat bear"],
	["ball python","royal python"],
	["ankole watusi","ankole longhorn", "ankole cattle","watusi", "ankole watusi", "ankole longhorn"],
	["tomistoma","false gharial"],
	["asian black bear","moon bear", "white chested bear"],
	["sloth bear","labiated bear"],
	["harris hawk","harris' hawk", "harris's hawk"],
	["peacock","peafowl"],
	["common kestral","european kestral","eurasian kestral","old world kestral"],
	["capybara","water cavy"],
	["votsovotsa","malagasy giant jumping rat","giant jumping rat"],
	["aonyx cinereus","amblonyx cinereus","aonyx cinerea","amblonyx cinerea"],
	["brown mantled tamarin","saddleback tamarin"],
	["brush tailed bettong","woylie"],
	["red winged macaw","red and green macaw"],
	["white stork", "european stork"],
	["sulcate tortoise","african spurred tortoise","giant spurred tortoise"],
	["european eagle owl","eurasian eagle owl"],
	["black chested buzzard eagle","black buzzard eagle","grey buzzard eagle","chilean blue eagle"],
	["red-billed leiothrix","pekin robin"],
	["java sparrow","java finch"],
	["brown rat","common rat","street rat","sewer rat","hanover rat","norway rat","brown norway rat","norwegian rat","wharf rat"],
	["taiwan beauty rat snake","beauty ratsnake","beauty snake","cave racer"],
	["pied tamarin","brazilian bare faced tamarin"],
	["white faced saki monkey","guianan saki","golden faced saki"],
	["white headed marmoset","tufted ear marmoset","geoffroy's marmoset","geoffroy's marmoset"],
	["oncilla","little spotted cat","tigrina","tigrillo","tiger cat"],
	["corsac fox","corsac"],
	["lar gibbon","white handed gibbon"],
	["bennetts wallaby","red necked wallaby"],
	["parma wallaby","white throated wallaby"],
	["swamp wallaby","black wallaby"],
	["giant anteater","ant bear"],
	["swamp cavy","greater guinea pig"],
	["damara zebra","burchells zebra"],
	["southern cassowary","double-wattled cassowary","two wattled cassowary","australian cassowary"],
	["manchurian crane","red crowned crane"],
	["australian wattled plover","masked lapwing"],
	["red legged seriema","crested seriema"],
	["bali mynah","rothschilds mynah"],
	["northern white faced owl","white faced scops owl"],
	["sungazer","giant girdled lizard"],
	["spot necked otter","spotted necked otter","speckle throated otter"]
	];